global:
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  consulCatalog:
    endpoint:
      address: http://consul:8500
    exposedByDefault: false
    refreshInterval: 15s

  file:
    filename: /etc/traefik/config.yml
    watch: true


log:
  level: DEBUG
  format: common

entryPoints:
  redis:
    address: ":6379"
  postgresql:
    address: ":5432"
  mysql:
    address: ":3306"
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
